plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mohammadgoudarzi.installments'
    compileSdk 35

    defaultConfig {
        applicationId 'com.mohammadgoudarzi.installments'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '1.0'
    }

    packaging {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt'
            ]
        }
    }
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

dependencies {
}
